server:
  port: 0
spring:
  cloud:
    stream:
      function:
        definition: convertToBaseCurrency
      bindings:
        convertToBaseCurrency-in-0:
          destination: NGN-PAYMENTS-REQUESTS,USD-PAYMENTS-REQUESTS,EUR-PAYMENTS-REQUESTS
          content-type: application/json
        convertToBaseCurrency-out-0:
          destination: BASE-PAYMENT-REQUEST
          content-type: application/json
  kafka:
    consumer:
      auto-offset-reset: earliest
